
server:
  port: 8081
  servlet:
    context-path: /luckeymoney

limit:
  minMoney: 2
  max-money: 9999
  description: 最少要发${limit.min-money},最多要发${limit.max-money}
spring:
  profiles:
    active: dev


