
server:
  port: 8081
  servlet:
    context-path: /luckeymoney

limit:
  minMoney: 0.1
  max-money: 9999
  description: 最少要发${limit.min-money},最多要发${limit.max-money}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/luckeymoney?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true